%YAML 1.2
---
# Summarizes a text by extracting the most relevant sentences.
transformers:
    - freeling_parse
    - pos_extract
    - sim_link
    - extend
    - unique
    - sentences
transformer_args:
    sempos: { noun: n }
    unique_gram: { hyper: [ True ] }
    extended_sentence_edges: [ HYP ]
operations:
    - op: cluster
      hubratio: 0.2
#    - op: markov_cluster
#      expand_factor: 10
#      inflate_factor: 2
#      max_loop: 10
#      mult_factor: 1
#    - op: louvain_cluster
linearizers:
    - cluster_extract
linearizer_args:
    summary_length: 100
    summary_margin: 10
    normalize_sentence_scores: True
